apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: foodexpress

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "foodexpress"

        vault.hashicorp.com/agent-requests-cpu: "50m"
        vault.hashicorp.com/agent-requests-mem: "32Mi"


        # Secret path in Vault
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/foodexpress"

        # Create /vault/secrets/config
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/foodexpress" -}}
          DB_USER={{ .Data.data.DB_USER }}
          DB_PASSWORD={{ .Data.data.DB_PASSWORD }}
          API_KEY={{ .Data.data.API_KEY }}
          {{- end }}

    spec:
      serviceAccountName: backend-sa

      containers:
      - name: backend
        image: madhu934652/food-express-backend:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: foodexpress-config
              key: DB_HOST

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: foodexpress-config
              key: DB_PORT

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: foodexpress-config
              key: DB_NAME

        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: foodexpress-config
              key: NODE_ENV

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: foodexpress-config
              key: PORT

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10